// Mocks generated by Mockito 5.4.4 from annotations
// in quick_lingo/test/features/auth/data/data_sources/auth_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:quick_lingo/core/network/api_response.dart' as _i2;
import 'package:quick_lingo/core/network/api_service.dart' as _i3;
import 'package:quick_lingo/core/network/responses/auth/sign_in_response.dart'
    as _i5;
import 'package:quick_lingo/core/network/resquests/auth/sign_in_request.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.SignInResponse>> signIn(
          _i6.SignInRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [request],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.SignInResponse>>.value(
            _FakeApiResponse_0<_i5.SignInResponse>(
          this,
          Invocation.method(
            #signIn,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.SignInResponse>>);
}
